dataset_path: lmms-lab/LMMs-Eval-Lite
dataset_name: gqa
dataset_kwargs:
  token: True
task: gqa
test_split: lite
output_type: generate_until
doc_to_visual: !function utils.gqa_doc_to_visual
doc_to_text: !function utils.gqa_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 1024  #TODO
  temperature: 0.2
  top_p: 0
  num_beams: 1 
  do_sample: True

metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
metadata:
  - version: 0.0

process_results: !function utils.gqa_process_results
# process_results: !function utils.egothink_process_results

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."
  qwen_vl:
    pre_prompt: ""
    post_prompt: " Answer:"