task: ok_vqa
test_split: lite 
dataset_path: lmms-lab/LMMs-Eval-Lite
dataset_name: ok_vqa_val2014
output_type: generate_until
dataset_kwargs:
  token: True
  
doc_to_visual: !function utils.ok_vqa_doc_to_visual
doc_to_text: !function utils.ok_vqa_doc_to_text
doc_to_target: "answer"

generation_kwargs:
  max_new_tokens: 1024  #TODO
  temperature: 0.2
  top_p: 0
  num_beams: 1 
  do_sample: True
  # modalities: ["video"]

metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
  - metric: submission
    aggregation: !function utils.ok_vqa_aggregate_submissions
    higher_is_better: true
process_results: !function utils.ok_vqa_process_results
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nWhen the provided information is insufficient, respond with 'Unanswerable'.\nAnswer the question using a single word or phrase."
metadata:
  - version: 0.0